### ISSUE TITLE
Quickstart issues

### ISSUE THREAD

**Issue by erikv05** [elmisback/magic-markup#1]
After following the quickstart, I got the following error:

<img width="622" alt="Screenshot 2024-06-18 at 5 46 46 PM" src="https://github.com/elmisback/magic-markup/assets/97545373/2398fc63-c6d2-4b82-b371-a721068dc62d">

After reinstalling npm with:
`rm -rf /usr/local/lib/npm
nvm install 20`

I reran and got this error: 

<img width="621" alt="Screenshot 2024-06-18 at 5 47 48 PM" src="https://github.com/elmisback/magic-markup/assets/97545373/7ab628f3-4248-4655-ab4e-81c4505bcdb5">

After running:

`npm i openai`

The retag server was successfully started. I ran into an error (reading 'leftIdx') but this was due to having saved OPENAI_API_KEY as an environment variable via zsh. After removing this variable, codetations read the api key from the .env file and the retag server worked.

**Comment by elmisback** [comment]
Looks like the first error was just a version issue.

I added the openai dependency to the package json -- you can make this kind of dependency update yourself, you don't need to ask permission!

The final error is probably some kind of issue with the response coming back from the API, we'll need to look at that and debug as a separate issue.
